image: techindicium/snowflake-base:latest

pipelines:
  pull-requests:
    '**':
      - step:
          name: Static Analysis Test
          script:
            - bash ${BITBUCKET_CLONE_DIR}/scripts/terraform.sh setup_environment
            - bash ${BITBUCKET_CLONE_DIR}/scripts/terraform.sh static_analysis_test
            
      - step:
          name: Unit and Integration Test
          script:
            - bash ${BITBUCKET_CLONE_DIR}/scripts/terraform.sh setup_environment
            - bash ${BITBUCKET_CLONE_DIR}/scripts/terraform.sh integration_test
