image: golang:latest

pipelines:
  pull-requests:
    '**':
      - step:
          name: Terraform Lint
          image: ghcr.io/terraform-linters/tflint:v0.48.0
          script:
            - $TFLINT_SETUP_COMMAND
            - cd ${BITBUCKET_CLONE_DIR}/tests
            - tflint --init
            - tflint

      - step:
          name: Static Analysis Test
          script:
            - $TERRAFORM_SETUP_COMMAND
            - cd ${BITBUCKET_CLONE_DIR}/tests
            - $TERRAFORM_STATIC_ANALYSIS_COMMAND
            
      - step:
          name: Unit and Integration Test
          script:
            - $TERRAFORM_SETUP_COMMAND
            - cd ${BITBUCKET_CLONE_DIR}/tests
            - $TERRAFORM_INTEGRATION_TEST_COMMAND

definitions:
  caches:
    tflint: ~/.tflint-cache

variables:
  TFLINT_SETUP_COMMAND: bash ${BITBUCKET_CLONE_DIR}/scripts/terraform.sh setup_environment
  TERRAFORM_SETUP_COMMAND: bash ${BITBUCKET_CLONE_DIR}/scripts/terraform.sh setup_environment
  TERRAFORM_STATIC_ANALYSIS_COMMAND: bash ${BITBUCKET_CLONE_DIR}/scripts/terraform.sh static_analysis_test
  TERRAFORM_INTEGRATION_TEST_COMMAND: bash ${BITBUCKET_CLONE_DIR}/scripts/terraform.sh integration_test