image: golang:latest

pipelines:
  pull-requests:
    '**':
      - step:
          name: Static Analysis Test
          script:
            - bash ${BITBUCKET_CLONE_DIR}/scripts/terraform.sh setup_environment
            - cd ${BITBUCKET_CLONE_DIR}/tests
            - bash ${BITBUCKET_CLONE_DIR}/scripts/terraform.sh static_analysis_test
      # - step:
      #     name: Unit and Integration Test
      #     script:
      #       - cd ${BITBUCKET_CLONE_DIR}/tests
      #       - bash ${BITBUCKET_CLONE_DIR}/scripts/terraform_test.sh