image: golang:latest

pipelines:
  pull-requests:
    '**':
      - step:
          name: Terraform Lint
          image: ghcr.io/terraform-linters/tflint:v0.48.0
          script:
            - cd ${BITBUCKET_CLONE_DIR}/tests
            - terraform init -backend-config="key=${BACKEND_KEY}" -backend-config="bucket=${BACKEND_BUCKET}" -backend-config="region=${AWS_REGION}"
            - tflint --init
            - tflint

      - step:
          name: Static Analysis Test
          script:
            - bash ${BITBUCKET_CLONE_DIR}/scripts/terraform.sh setup_environment
            - cd ${BITBUCKET_CLONE_DIR}/tests
            - bash ${BITBUCKET_CLONE_DIR}/scripts/terraform.sh static_analysis_test
            
      - step:
          name: Unit and Integration Test
          script:
            - bash ${BITBUCKET_CLONE_DIR}/scripts/terraform.sh setup_environment
            - cd ${BITBUCKET_CLONE_DIR}/tests
            - bash ${BITBUCKET_CLONE_DIR}/scripts/terraform.sh integration_test
