image: golang:latest

pipelines:
  pull-requests:
    '**':
      - step:
          name: Terraform Lint
          image: ghcr.io/terraform-linters/tflint:v0.48.0
          script:
            - bash ${BITBUCKET_CLONE_DIR}/scripts/terraform.sh setup_environment
            - cd ${BITBUCKET_CLONE_DIR}/tests
            - tflint --init
            - tflint

      - step:
          name: Static Analysis Test
          script:
            - bash ${BITBUCKET_CLONE_DIR}/scripts/terraform.sh setup_environment
            - cd ${BITBUCKET_CLONE_DIR}/tests
            - bash ${BITBUCKET_CLONE_DIR}/scripts/terraform.sh static_analysis_test
            
      - step:
          name: Unit and Integration Test
          script:
            - bash ${BITBUCKET_CLONE_DIR}/scripts/terraform.sh setup_environment
            - cd ${BITBUCKET_CLONE_DIR}/tests
            - bash ${BITBUCKET_CLONE_DIR}/scripts/terraform.sh integration_test
