# image: golang:latest

# pipelines:
#   pull-requests:
#     '**':
#       - step:
#           name: Test Snowflake Base Module
#           script:
#             - bash ${BITBUCKET_CLONE_DIR}/scripts/terraform.sh